extends: airbnb-base
rules:
  no-underscore-dangle: 0
  no-param-reassign: 0
  class-methods-use-this: 0
  import/prefer-default-export: 0
  no-console: 0
  no-plusplus: 0
  import/no-extraneous-dependencies: 0
  no-use-before-define: 0